# Generated by Django 5.2.3 on 2025-07-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='status',
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Ausente', max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubs')),
            ],
        ),
    ]
