# Generated by Django 5.2.3 on 2025-06-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='status',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Ausente', max_length=20),
        ),
    ]
